### ISSUE TITLE
parse_quotable_robust: no message for exception

### ISSUE THREAD

**Issue by noraj** [ruby/csv#208] opened 2021-03-02 16:20 UTC
https://github.com/ruby/csv/blob/fd86afe0814bcc236ae81a4269158654d1b83223/lib/csv/parser.rb#L933-L934

**Comment by kou** [comment] 2021-03-02 21:30
Could you show a CSV that reaches there?

**Comment by noraj** [comment] 2021-03-02 21:42
https://raw.githubusercontent.com/ihebski/DefaultCreds-cheat-sheet/main/DefaultCreds-Cheat-Sheet.csv

As soon as I use `strip: true`

**Comment by kou** [comment] 2021-03-24 08:27
Could you also provide a script that reproduces this case?

I couldn't reproduce with the following script:

```ruby
#!/usr/bin/env ruby

require "csv"
require "open-uri"

p CSV::VERSION

URI.open("https://raw.githubusercontent.com/ihebski/DefaultCreds-cheat-sheet/main/DefaultCreds-Cheat-Sheet.csv") do |input|
  csv = CSV.new(input, strip: true)
  p csv.to_a.size
end
```

Output:

```text
"3.2.0"
3344
```

**Comment by noraj** [comment] 2021-03-24 14:37
@kou Yes I was using it in [this project](https://github.com/sec-it/pass-station). The config is done [there](https://github.com/sec-it/pass-station/blob/master/lib/pass_station/parse.rb).

## Example

I just retried now.

```
$ git clone https://github.com/sec-it/pass-station.git
$ cd pass-station
$ bundle install
$ ruby -Ipass-station/lib -rpass_station bin/pass-station list
```

- ✅ Using strip converter (actual code)
- ✅ Using `strip: true` config option

```diff
-      strip_converter = proc { |field| field.strip }
-      CSV::Converters[:strip] = strip_converter
+      @config[:strip] = true
-      @config[:converters] = :strip
```

It works now, but since I first open the issue I cleaned the CSV input file a lot (see https://github.com/ihebski/DefaultCreds-cheat-sheet/pull/8). Before this time, the strip converter was working and `strip: true` option was crashing even when using `liberal_parsing: true` certainly because there was some malformation in the input file.

Seems to work now but the converter and the `strip: true` option may not be executed at the same phase of the parsing,the converter may happen before which make it more resilient. With `strip: true` I felt like a pre-parsing was done the stripping and so malformation raise an error before the document has been stripped.

Since I didn't save any proof and it's not reproducible at this time I feel ok if you want to close the issue.

**Comment by kou** [comment] 2021-03-27 21:43
OK.

I also tried more patterns with https://github.com/ihebski/DefaultCreds-cheat-sheet/commit/8c973685f4b42132dbb5c462fd01a8b3c1d454fb but I also couldn't reproduce. So I close this.

Sorry for not confirming this quickly.

**Closed by kou** 2021-03-27 21:43 UTC
